server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmily_order?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: hmily.dubbo.common.order.entity
  config-location: classpath:mybatis-config.xml

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: debug
    io.github.brightloong: debug
  path: "./logs"