spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      write:
        url:
        username:
        password:
      read:
        url:
        username:
        password: !